module.exports = [{
      name: "Kimbe Bay",
      temperature:  "30°C-32°C",
      description: "Divers don’t come to Kimbe Bay for the big sharks or manta rays, but rather the macro photography opportunities and huge diversity of fish. Diving here could be compared to being inside a fully stocked aquarium. There are dozens of dive sites to choose from in the area, and they can basically be put in one of two groups: well-developed reefs near shore and intriguing sea-mounts and pinnacles (such as Bradford Shoals) which rise up from the deeper offshore waters of the bay. Try them all if you get there, and you’ll be the envy of many divers who’d love to put this place in their dive logs!",
      language: "English",
      country: "Papua New Guinea",
      requirement: "PADI Advance Open Water,PADI Open Water",
      currency: "Papua New Guinean Kina",
      poster: "http://www.indopacificimages.com/wp-content/uploads/2012/08/TNC_Schumann-Island_400.jpg",
      id: "tt0133093",
    }, {
      name: "Sipadan",
      temperature:  "30°C-32°C",
      description: "Sipadan is a small island– about 30 acres total– that lies on the border of Indonesia and Malaysia in Borneo. Most dive pros (including the legendary Jacques-Yves Cousteau) agree that the numerous sites found around Sipadan Island deserve to be listed among the world’s best places to Scuba dive. Sites with names like Lobster Wall, Froggie Lair, Barracuda Point and Turtle Cave basically say it all..",
      language: "English, Malay",
      season: "All year",
      country: "Malaysia",
      requirement: "PADI Advance Open Water,PADI Open Water",
      currency: "Ringgit Malaysia",
      poster: "http://pulaupulau.com/images/sipadan/sipadan.jpg",
      id: "tt1276104",
    }, {
      name: "Dahab",
      temperature:  "30°C-32°C",
      description: "There is one up-side to the constant revolutions and turmoil in Egypt: For the most part, tourists have stayed away, and the epic reef system and marine life have been allowed to flourish.",
      language: "English,Arabic",
      season: "All year",
      country: "Egypt",
      requirement: "PADI Advance Open Water,PADI Open Water",
      currency: "Egyptian pound",
      poster: "http://cdn.wanderlust.co.uk/contentimages/wanderlust/li-215.jpg?maxwidth=460",
      id: "tt1104001",
    }, {
      name: "Kona Mantas, Hawaii",
      temperature:  "30°C-32°C",
      description: "If you ever wanted to get up close and personal with giant manta rays, this is the best place to do it. Kona Mantas also attracts tons of dolphins, humpback whales and other big fish, but they are most famous for their giant mantas. The most popular dive here is the nighttime one, wherein divers kneel in the sand and shine their lights up to illuminate the plankton. Then the giant mantas– some with a span of 16 feet– come gliding in to put on a memorable show.",
      language: "English, Japanese",
      country: "USA",
      requirement: "PADI Advance Open Water,PADI Open Water",
      currency: "USD",
      poster: "https://s-media-cache-ak0.pinimg.com/236x/4c/75/2f/4c752f59ea438e6d9c7a09716d30b4f2.jpg",
      id: "tt1375666",
    }, {
      name: "Arch of Darwin",
      temperature:  "30°C-32°C",
      description: "If you’re more into giant marine species than reef landscapes and macro photography, this is probably the best dive site in the world for you. Here is a preview of the lineup that you’re likely to see in ONE dive: massive whale sharks, ample Galapagos sharks, more sea turtles than you can imagine, tiger sharks on the safety stop, giant free-swimming moray eels, huge eagle rays, and enough hammerhead sharks circling above you that they blot out the sunlight. I’m pretty sure you’ll wind up declaring this the best dive of your life.",
      language: "Spanish",
      country: "Ecuador",
      requirement: "PADI Advance Open Water,PADI Open Water",
      currency: "USD",
      poster: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Darwinarch.jpg",
      id: "tt0945513",
    }, {
      name: "The San Francisco Maru",
      temperature:  "30°C-32°C",
      description: "Discovered in 1972, the San Francisco Maru sits upright. The cargo holds contain sea mines, torpedoes, bombs, artillery, aircraft engines, anti-tank and small arms munitions, two Japanese tanks and many more WW2 artifacts. This is a deep, technical dive at between 40-58 meters, but is a must-see for those who qualify. As one of the biggest, most well-preserved shipwrecks in the world, the San Francisco Maru is worth a trip to Micronesia in and of itself. But if that’s not enough for you, the islands dotted around the area are littered with tons of WW2 wrecks, many of which lie in shallow depths",
      language: "English",
      country: "Micronesia",
      requirement: "Wreck Diving,PADI Advance Open Water,PADI Open Water",
      currency: "USD",
      poster: "https://s-media-cache-ak0.pinimg.com/originals/fc/5a/75/fc5a755ba6ba4f23160d7f651cc0663e.jpg",
      id: "tt0113243",
    }, {
      name: "Cocos Island",
      temperature:  "30°C-32°C",
      description: "Cocos Island is one of the more difficult and expensive dive locations on the list to get to, but it’s a must-see for scuba lovers. The island is more than 300 miles offshore from Costa Rica, and is highly protected (i.e. all human habitation is prohibited). The only way to dive it is on live-aboard ships from the mainland. But this amazing marine reserve was listed as a candidate for the new 7 Wonders of Nature, and ranked second in the islands category. If you’ve ever yearned to be in the middle of a giant tornado of hammerhead sharks and barracudas, this is the place",
      language: "Spanish",
      country: "Costa Rica",
      requirement: "PADI Advance Open Water,PADI Open Water",
      currency: "Costa Rican colón",
      poster: "http://ns.gov.gu/icons/cocos.isle.jpg",
      id: "tt1285016",
    }, {
      name: "Secret Bay, Anilao",
      temperature:  "30°C-32°C",
      description: "Anilao is a macro heaven for underwater photographers, offering an incredible variety of tiny species. If you’re a nudibranch lover, this is definitely the place you’ll find them. Anilao is located about 3 hours south of Manila on the island of Luzon, in the Batangas province of the Philippines. So it’s fairly easy to get there. Divers are drawn to this place because of its healthy reef and sheer numbers of macro critters and unique species. It should definitely be on your diving bucket list, but it will spoil you for any future diving you do!",
      language: "English, Tagalog",
      country: "Philippines",
      requirement: "PADI Advance Open Water,PADI Open Water",
      currency: "Peso",
      poster: "http://www.acaciadive.com/img/divers4.jpg",
      id: "tt2084970",
    }, {
      name: "Roatan, Bay Islands",
      temperature:  "30°C-32°C",
      description: "The best dive site in Roatan is perhaps Mary’s Place. It has a sheer-walled crevasse advanced divers can explore (or beginners can dive over) and see out-of-this-world sights such as black coral fans, anemones, huge seahorses, giant rainbow parrotfish and tons of alien-looking formations. This memorable site is not only a must-see, but it’s also one of the cheapest to get to and dive. So there are no excuses not to check out the virtually guaranteed abundant and colorful marine life.",
      language: "Spanish",
      country: "Honduras",
      requirement: "PADI Advance Open Water,PADI Open Water",
      currency: "Honduran lempira",
      poster: "http://www.islandroseroatan.com/wp-content/uploads/2012/07/Beautiful-Island-of-Roatan-Bay-Islands-Honduras-by-Island-Rose-Roatan-Home-Rentals-1.jpg",
      id: "tt0151804",
    }]